// <reference types="cypress" />

describe('Cypress basics', () => {
    it('Visitar', () => {
        cy.visit('http://localhost:3000/')
    })

    it('Chackbox', () => {
        cy.get(':nth-child(2) > #clickAll')
            .click()
            .should('be.checked')

        cy.get(':nth-child(3) > #clickAll')
            .click()
            .should('be.checked')

        cy.get(':nth-child(4) > #clickAll')
            .click()
            .should('be.checked')
        
        cy.get(':nth-child(5) > #clickAll')
            .click()
            .should('be.checked')
        cy.get(':nth-child(6) > #clickAll')
            .click()
            .should('be.checked')
    })

    it('Chackbox', () => {
        cy.get("#clickViewListing")
            .click()
            .should('not.be.checked')
        cy.get("#clickViewDetails")
            .click()
            .should('not.be.checked')
        cy.get("#clickCreate")
            .click()
            .should('not.be.checked')
        cy.get("#clickEdit")
            .click()
            .should('not.be.checked')
        cy.get("#clickDelete")
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(5) > :nth-child(2) > #clickViewListing')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(5) > :nth-child(3) > #clickViewDetails')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(5) > :nth-child(4) > #clickCreate')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(5) > :nth-child(5) > #clickEdit')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(5) > :nth-child(6) > #clickDelete')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(9) > :nth-child(2) > #clickViewListing')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(9) > :nth-child(3) > #clickViewDetails')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(9) > :nth-child(4) > #clickCreate')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(9) > :nth-child(5) > #clickEdit')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(9) > :nth-child(6) > #clickDelete')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(14) > :nth-child(2) > #clickViewListing')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(14) > :nth-child(3) > #clickViewDetails')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(14) > :nth-child(4) > #clickCreate')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(14) > :nth-child(5) > #clickEdit')
            .click()
            .should('not.be.checked')
        cy.get(':nth-child(14) > :nth-child(6) > #clickDelete')
            .click()
            .should('not.be.checked')
    })
})